version: '3.11'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: kaizntree_db
    image: postgres:12
    environment:
      - POSTGRES_USER=kaizntree
      - POSTGRES_PASSWORD=kaizntree
      - POSTGRES_DB=kaizntree
    ports:
      - 5433:5433
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
