version: '3.11'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8001'
    ports:
      - 8001:8001
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: kaizntree_db
    image: postgres:12
    environment:
      - POSTGRES_USER=kaizntree
      - POSTGRES_PASSWORD=kaizntree
      - POSTGRES_DB=kaizntree
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
