# Generated by Django 5.0 on 2024-02-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
