# Generated by Django 5.0 on 2024-02-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_dashboard', '0002_rename_items_item_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='items_dashboard.tag'),
        ),
    ]
